### ISSUE TITLE
Getting a Vagrant error on OS X 10.11.1

### ISSUE THREAD

**Issue by chrisfried** [hashicorp/otto-getting-started#3]
```
$ otto dev
==> Creating local development environment with Vagrant if it doesn't exist...
    Raw Vagrant output will begin streaming in below. Otto does
    not create this output. It is mirrored directly from Vagrant
    while the development environment is being created.

/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/root.rb:50:in `block in finalize!': undefined method `finalize!' for []:Array (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/root.rb:49:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/root.rb:49:in `finalize!'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:21:in `finalize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:158:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in `host'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `ensure in <main>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'

Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
```

Reinstalled Vagrant for good measure, still getting this.

**Comment by guycalledseven** [comment]
This looks like an error I was getting before I updated parallels plugin.
If you are using paralles as hypervisor execute this from terminal
`vagrant plugin install vagrant-parallels`

then in your .bashrc_profile add
`export VAGRANT_DEFAULT_PROVIDER=parallels`

restart terminal an retry.
if that doesn't work then do `vagrant global-status` and delete orphans and retry.

**Comment by ghost** [comment]
Also have the error on a fresh install:

```
otto-getting-started]$ otto dev
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Creating layer: consul
Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
```
